name: ci-insights
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fake tests
        id: tests
        continue-on-error: true
        run: cp junit.xml report.xml
      - name: mergify ci
        uses: Mergifyio/gha-mergify-ci@main
        with:
          action: junit-process
          token: ${{ secrets.MERGIFY_CI_TOKEN }}
          report_path: report.xml
          job_name: ci-insights-test
